config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # read all tasks
  get 'tasks', to: 'tasks#index', as: :tasks
  # create one task
  post 'tasks', to: 'tasks#create'

  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  # read one task
  get 'tasks/:id', to: 'tasks#show', as: :task
  # update one task
  patch 'tasks/:id', to: 'tasks#update'
  #delete one task
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # read all tasks, plural
  def index
    @tasks = Task.all
  end

  # read one task, singular
  def show
  end

  # create a new task
  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path
  end

  def edit
  end

  # update a task
  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  # delete a task
  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  # for security

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title, "Enter a title" %>
  <%= f.text_field :title %>
  <%= f.label :details, "Enter details" %>
  <%= f.text_area :details %>
  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :completed %> Completed
      </label>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>










<!-- <form action="/tasks" method="post">

  <label for="name">Enter a title</label>
  <input type="text" name="task[title]">

  <label for="name">Enter details</label>
  <input type="text" name="task[details]">

 <label for="name">Tick the box when complete</label>
  <input type="text" name="task[completed]">


  <input type="submit">

</form>-->

app/views/tasks/index.html.erb
<h1>Your tasks</h1>

<%= link_to "Add a task", new_task_path %>

<% @tasks.each do |task| %>
  <h2><%= link_to task.title, task_path(task.id) %></h2>
  <p><%= task.details %></p>
  <p><%= task.completed %></p>
  <%= link_to "Remove a task", task_path(task), method: :delete %>
<% end%>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
  <p><%= @task.completed %></p>

  <%= link_to "back to all tasks", tasks_path %>